title: <p align="center"> Mihir Pawar </p>
logo: /assets/img/Mihir Pawar.jpg


description:
  <a href="docs/Mihir Pawar_Data Science(Jan 2021).pdf" >Resume</a> |
  <a href="https://www.linkedin.com/in/mihir-pawar-49193518a/">LinkedIn</a> |
  <a href="https://github.com/DataScientist365">GitHub</a> |
  <a href="https://public.tableau.com/app/profile/mihir.pawar#!/">Tableau</a>
  
  <br>   
  I am a Data Science Enthusiast.
  I am currently working at Brandscapes Worldwide as Executive Software Development, Analytics.
  I have worked on Data Science, Machine Learning, Data Analytics projects.
  <br>
  </p>



theme: jekyll-theme-minimal
