title: <p align="center"> Mihir Pawar </p>
logo: /assets/img/Mihir Pawar.jpg


description:
  <p align="center">
  <a href="docs/Mihir Pawar_Data Science(Jan 2021).pdf" >Resume</a> |
  <a href="https://www.linkedin.com/in/mihir-pawar-49193518a/">LinkedIn</a> |
  <a href="https://github.com/DataScientist365">GitHub</a> 
  
  <br>
  Executive Software Development, Analytics at Brandscapes Worldwide
  Worked on building Data Science, Machine Learning, Data Analytics projects
  <br>
  </p>



theme: jekyll-theme-minimal
