title: <p align="center"> Mihir Pawar </p>
logo: /assets/img/Mihir Pawar.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mihir-pawar-49193518a/">LinkedIn</a> |
  <a href="https://github.com/DataScientist365">GitHub</a>
  <a href="https://public.tableau.com/app/profile/mihir.pawar#!/">Tableau</a>
  
  <br>
  I am a Data Science Enthusiast working at Brandscapes Worldwide as Executive Software Development, Analytics from January 2021.
  I have worked on Data Science, Machine Learning, Data Analytics projects.
  Currently, I am applying the knowledge gained in Data Science in different domains such as Healthcare, E-commerce, Finance, Retail, Human Resource,etc by working with APIs and industry data.
  <br>
  </p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
