title: <p align="center"> Mihir Pawar </p>
logo: /assets/img/Mihir Pawar.jpg


description:
  <p align="center">
  <a href="docs/Mihir Pawar_Data Science(Jan 2021).pdf" >Resume</a> |
  <a href="https://www.linkedin.com/in/mihir-pawar-49193518a/">LinkedIn</a> |
  <a href="https://github.com/DataScientist365">GitHub</a> 
  
   <h4>Executive Software Development, Analytics</h4>
   <h4>Worked on Data Science, Machine Learning, Data Analytics projects</h4>
  
  <br>
  </p>



theme: jekyll-theme-minimal
